### ISSUE TITLE
Pharos Controls LPC

### ISSUE THREAD

**Issue by fvw75** [bitfocus/companion-module-pharos-designer#1]
Hi , 

Please try to make a module for the pharos controls LPC Light controller ..

run / stop timeline would be nice 

thank you

https://www.pharoscontrols.com/downloads/documentation/application-notes/

**Comment by josephdadams** [comment]
@hartmann-jonas is this the module you’re working on

**Comment by hartmann-jonas** [comment]
Yes, it is

**Comment by hartmann-jonas** [comment]
The module is fully developed and just needs to be added in Companion

**Comment by josephdadams** [comment]
It hath been added
